### ISSUE TITLE
Add co-champions to this repository

### ISSUE THREAD

**Issue by merlijn-sebrechts** [WebAssembly/wasi-i2c#11]
Hi @ricochet, @pchickey

Is it possible to add the two co-champions to this repository?

Specifically, 

- Merlijn Sebrechts @merlijn-sebrechts
- Maximilian Seidler @mxsdlr

Thanks!

**Comment by ricochet** [comment]
Invites sent your way!

**Comment by merlijn-sebrechts** [comment]
@ricochet I'm so sorry, I thought I accepted the invitation but it wasn't the case. The invitation has since expired. Can you send it again?

**Comment by ricochet** [comment]
@merlijn-sebrechts resent. Will you let me know if this works for you?

**Comment by merlijn-sebrechts** [comment]
@ricochet It works now, thanks!!
